version: '3'
services:
    mybuntu:
        image: ubuntu:latest
        restart: always
        ports:
            - "8080:80"
        command: bash -c ${LONGCOMMAND}

    mydeb0:
        image: debian:latest
        restart: always
        ports:
            - "9090:80"
        links:
            - mybuntu
        command: bash -c ${LONGCOMMAND}

    mydeb1:
        image: debian:latest
        restart: always
        ports:
            - "7070:80"
        links:
            - mybuntu
        command: bash -c ${LONGCOMMAND}
        